version: '3'
services:
  web:
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - LOG_LEVEL=debug
    #command: /start-reload.sh
